matrix:
  include:
    -  os: linux
       dist: trusty
    -  os: osx

language: r
sudo: required
       
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew unlink cmake; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cmake; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install clang-omp; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then CC="clang-omp"; CXX="clang-omp++"; fi
  - ./configure --enable-build-mincrepos:
  bioCsoft: http://bioconductor.org/packages/3.2/bioc
  cran: https://cran.rstudio.com
r_check_args: --install-args="--configure-args=\"--enable-build-minc\""


