language: r
sudo: required
dist: trusty
cache: packages
before_install:
  - ./configure --enable-build-minc
repos:
  bioCsoft: http://bioconductor.org/packages/3.2/bioc
  cran: https://cran.rstudio.com
r_check_args: --install-args="--configure-args=\"--enable-build-minc\""


